import type { Metadata } from "next";
import "./globals.css";
import AuthWrapper from "./AuthWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className="flex flex-row justify-center">
        <AuthWrapper>
          <div className="lg:w-1/2 mt-5">{children}</div>
        </AuthWrapper>
      </body>
    </html>
  );
}
